environment:
  domain: "dockerlab.local"
  swarm_masterip: "10.10.10.11"
  engine_version: "17.09.1~ce-0~ubuntu"
  experimental: true
  base_box: "frjaraur/xenial64"
  base_box_version: "1.2"
  #proxy: "http://your_proxy_goes_here:with_the_port"
  tls_enabled: true
  tls_passphrase: "changeme"
  rexray_enabled: true

boxes:
- name: "swarm1"
  swarm_role: "manager"
  mgmt_ip: "10.10.10.11"
  hostonly_ip: "192.168.56.11"
  mem: "1524"
  cpu: "1"

- name: "swarm2"
  swarm_role: "manager"
  mgmt_ip: "10.10.10.12"
  hostonly_ip: "192.168.56.12"
  mem: "1524"
  cpu: "1"

- name: "swarm3"
  swarm_role: "manager"
  mgmt_ip: "10.10.10.13"
  hostonly_ip: "192.168.56.13"
  mem: "1524"
  cpu: "1"
  
- name: "swarm4"
  swarm_role: "worker"
  mgmt_ip: "10.10.10.14"
  hostonly_ip: "192.168.56.14"
  mem: "1524"
  cpu: "1"
