environment:
  domain: "dockerlab.local"
  swarm_masterip: "10.10.10.11"
  #engine_version: "18.04.0~ce~3-0~ubuntu"
  engine_version: "latest"
  experimental: true
  base_box: "frjaraur/xenial64"
  base_box_version: "1.3"
  #proxy: "http://your_proxy_goes_here:with_the_port"
  tls_enabled: false
  tls_passphrase: "changeme"
 
storage:
 rexray_enabled: true
 minio_enabled: false
 minio_server: "swarm1"
 minio_access_key: "changeme"
 minio_secret_key: "changeme"
 nfs_enabled: true
 nfs_server: "swarm1"
 shared_mount: "/data"

boxes:
- name: "swarm1"
  swarm_role: "manager"
  mgmt_ip: "10.10.10.11"
  hostonly_ip: "192.168.56.11"
  mem: "1524"
  cpu: "1"

- name: "swarm2"
  swarm_role: "manager"
  mgmt_ip: "10.10.10.12"
  hostonly_ip: "192.168.56.12"
  mem: "1524"
  cpu: "1"

- name: "swarm3"
  swarm_role: "manager"
  mgmt_ip: "10.10.10.13"
  hostonly_ip: "192.168.56.13"
  mem: "1524"
  cpu: "1"
  
- name: "swarm4"
  swarm_role: "worker"
  mgmt_ip: "10.10.10.14"
  hostonly_ip: "192.168.56.14"
  mem: "1524"
  cpu: "1"
