version: "3"
# A Docker Compose file for deploying Visualizer (https://github.com/ManoMarks/docker-swarm-visualizer)

services:  
  visualizer:
    image: localhost:5000/manomarks/visualizer
    ports:
      - "8081:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

