version: "3.1"

services:
  # load balancer
  lb:
    image: hopla/mentorsday-lab:simplestlb
    environment:
      - APPLICATION_ALIAS=simplestapp
      - APPLICATION_PORT=3000
    networks:
      simplestdemo:
          aliases:
          - simplestlb
    ports:
      - 8080:80

  db:
    image: hopla/mentorsday-lab:simplestdb
    secrets:
      - source: "postgres"
        target: "postgres"
        uid: "0"
        gid: "0"
        mode: 0444
    environment:
        - "POSTGRES_PASSWORD_FILE=/run/secrets/postgres"
    networks:
       simplestdemo:
    volumes:
      - "PGDATA:/var/lib/postgresql/data"

  app:
    image: hopla/mentorsday-lab:simplestapp
    environment:
      - dbhost=simplestdb
      - dbname=demo
      - dbuser=demo
      - dbpasswd=d3m0
    networks:
       simplestdemo:
        aliases:
          - simplestapp
    depends_on:
      - lb
      - db

networks:
  simplestdemo:

volumes:
  PGDATA:
    driver: local

secrets:
  postgres:
    external:
      name: "simplestdemo_postgres"