version: "3.1"

services:
  # load balancer
  registry:
    image: registry
    ports:
      - 5000:5000
    volumes:
      - "REGISTRY:/var/lib/registry"
volumes:
  REGISTRY:
     driver: rexray
     driver_opts:
         size: 1

